---
title: "Задачи к курсу"
subtitle: "Статистический анализ данных"
author: "Дмитрий В. Наумов"
format:
  html:
    toc: false
---

[← Вернуться к курсу](../index.html){.exercise-back-link}

Материалы к готовым лекциям:

00. [Мотивация и обзор курса](00_introduction_exercises.html)
01. [Случайные величины, распределения, моменты](01_random_distributions_exercises.html)
02. [Характеристические функции и суммы случайных величин](02_characteristic_functions_exercises.html)
03. [Центральная предельная теорема и нормальное распределение](03_central_limit_theorem_exercises.html)
04. [Когда гаусс не возникает](04_non_gaussian_clt_violations_exercises.html)
05. [Распространение ошибок, ковариации и многомерный гаусс](05_error_propagation_and_covariance_exercises.html)
06. [Метод Монте-Карло и псевдоэксперименты](06_monte_carlo_method_exercises.html)
07. [Оценивание параметров и метод максимального правдоподобия](07_parameter_estimation_and_maximum_likelihood_exercises.html)
08. [Метод наименьших квадратов](08_method_of_least_squares_exercises.html)
09. [Статистические тесты: общие понятия](09_statistical_tests_basics_exercises.html)
10. [Статистики тестов и многомерные методы](10_test_statistics_and_multivariate_methods_exercises.html)
11. [Проверка согласия и статистическая значимость](11_goodness_of_fit_and_significance_exercises.html)
12. [Фельдман–Казинс, CLs и родственные методы](12_feldman_cousins_and_cls_exercises.html)
13. [Интервальные оценки и установление ограничений](13_interval_estimation_and_limits_exercises.html)
14. [Nuisance-параметры и систематические неопределённости](14_nuisance_parameters_and_systematics_exercises.html)
15. [Байесовский вывод и практические примеры](15_bayesian_examples_exercises.html)
